import Vue from 'vue'
import Router from 'vue-router'
import { normalizeURL, decode } from 'ufo'
import { interopDefault } from './utils'
import scrollBehavior from './router.scrollBehavior.js'

const _4016f643 = () => interopDefault(import('..\\pages\\about.vue' /* webpackChunkName: "pages/about" */))
const _54bbd613 = () => interopDefault(import('..\\pages\\agreeableness.vue' /* webpackChunkName: "pages/agreeableness" */))
const _5fced108 = () => interopDefault(import('..\\pages\\index.vue' /* webpackChunkName: "pages/index" */))
const _1d3982f7 = () => interopDefault(import('..\\pages\\articles.vue' /* webpackChunkName: "pages/articles" */))
const _6ba7b94b = () => interopDefault(import('..\\pages\\big_five.vue' /* webpackChunkName: "pages/big_five" */))
const _4947c7f2 = () => interopDefault(import('..\\pages\\compare\\index.vue' /* webpackChunkName: "pages/compare/index" */))
const _6331a585 = () => interopDefault(import('..\\pages\\conscientiousness.vue' /* webpackChunkName: "pages/conscientiousness" */))
const _f42fadfc = () => interopDefault(import('..\\pages\\extraversion.vue' /* webpackChunkName: "pages/extraversion" */))
const _3ac980cc = () => interopDefault(import('..\\pages\\faq.vue' /* webpackChunkName: "pages/faq" */))
const _6282eff4 = () => interopDefault(import('..\\pages\\neuroticism.vue' /* webpackChunkName: "pages/neuroticism" */))
const _c6157d6c = () => interopDefault(import('..\\pages\\openness_to_experience.vue' /* webpackChunkName: "pages/openness_to_experience" */))
const _20495d84 = () => interopDefault(import('..\\pages\\privacy.vue' /* webpackChunkName: "pages/privacy" */))
const _7132969e = () => interopDefault(import('..\\pages\\products.vue' /* webpackChunkName: "pages/products" */))
const _8211a96a = () => interopDefault(import('..\\pages\\result\\index.vue' /* webpackChunkName: "pages/result/index" */))
const _b1193868 = () => interopDefault(import('..\\pages\\test.vue' /* webpackChunkName: "pages/test" */))
const _0d7f742f = () => interopDefault(import('..\\pages\\compare\\_id.vue' /* webpackChunkName: "pages/compare/_id" */))
const _305d8473 = () => interopDefault(import('..\\pages\\result\\_id.vue' /* webpackChunkName: "pages/result/_id" */))

const emptyFn = () => {}

Vue.use(Router)

export const routerOptions = {
  mode: 'history',
  base: '/',
  linkActiveClass: 'nuxt-link-active',
  linkExactActiveClass: 'nuxt-link-exact-active',
  scrollBehavior,

  routes: [{
    path: "/about",
    component: _4016f643,
    name: "about___en"
  }, {
    path: "/agreeableness",
    component: _54bbd613,
    name: "agreeableness___en"
  }, {
    path: "/ar",
    component: _5fced108,
    name: "index___ar"
  }, {
    path: "/articles",
    component: _1d3982f7,
    name: "articles___en"
  }, {
    path: "/big_five",
    component: _6ba7b94b,
    name: "big_five___en"
  }, {
    path: "/compare",
    component: _4947c7f2,
    name: "compare___en"
  }, {
    path: "/conscientiousness",
    component: _6331a585,
    name: "conscientiousness___en"
  }, {
    path: "/da",
    component: _5fced108,
    name: "index___da"
  }, {
    path: "/de",
    component: _5fced108,
    name: "index___de"
  }, {
    path: "/es",
    component: _5fced108,
    name: "index___es"
  }, {
    path: "/extraversion",
    component: _f42fadfc,
    name: "extraversion___en"
  }, {
    path: "/faq",
    component: _3ac980cc,
    name: "faq___en"
  }, {
    path: "/fi",
    component: _5fced108,
    name: "index___fi"
  }, {
    path: "/fr",
    component: _5fced108,
    name: "index___fr"
  }, {
    path: "/hi",
    component: _5fced108,
    name: "index___hi"
  }, {
    path: "/id",
    component: _5fced108,
    name: "index___id"
  }, {
    path: "/is",
    component: _5fced108,
    name: "index___is"
  }, {
    path: "/it",
    component: _5fced108,
    name: "index___it"
  }, {
    path: "/ja",
    component: _5fced108,
    name: "index___ja"
  }, {
    path: "/neuroticism",
    component: _6282eff4,
    name: "neuroticism___en"
  }, {
    path: "/no",
    component: _5fced108,
    name: "index___no"
  }, {
    path: "/openness_to_experience",
    component: _c6157d6c,
    name: "openness_to_experience___en"
  }, {
    path: "/pl",
    component: _5fced108,
    name: "index___pl"
  }, {
    path: "/privacy",
    component: _20495d84,
    name: "privacy___en"
  }, {
    path: "/products",
    component: _7132969e,
    name: "products___en"
  }, {
    path: "/pt",
    component: _5fced108,
    name: "index___pt"
  }, {
    path: "/result",
    component: _8211a96a,
    name: "result___en"
  }, {
    path: "/ru",
    component: _5fced108,
    name: "index___ru"
  }, {
    path: "/sv",
    component: _5fced108,
    name: "index___sv"
  }, {
    path: "/test",
    component: _b1193868,
    name: "test___en"
  }, {
    path: "/th",
    component: _5fced108,
    name: "index___th"
  }, {
    path: "/uk",
    component: _5fced108,
    name: "index___uk"
  }, {
    path: "/zh-Hans",
    component: _5fced108,
    name: "index___zh-Hans"
  }, {
    path: "/ar/about",
    component: _4016f643,
    name: "about___ar"
  }, {
    path: "/ar/agreeableness",
    component: _54bbd613,
    name: "agreeableness___ar"
  }, {
    path: "/ar/articles",
    component: _1d3982f7,
    name: "articles___ar"
  }, {
    path: "/ar/big_five",
    component: _6ba7b94b,
    name: "big_five___ar"
  }, {
    path: "/ar/compare",
    component: _4947c7f2,
    name: "compare___ar"
  }, {
    path: "/ar/conscientiousness",
    component: _6331a585,
    name: "conscientiousness___ar"
  }, {
    path: "/ar/extraversion",
    component: _f42fadfc,
    name: "extraversion___ar"
  }, {
    path: "/ar/faq",
    component: _3ac980cc,
    name: "faq___ar"
  }, {
    path: "/ar/neuroticism",
    component: _6282eff4,
    name: "neuroticism___ar"
  }, {
    path: "/ar/openness_to_experience",
    component: _c6157d6c,
    name: "openness_to_experience___ar"
  }, {
    path: "/ar/privacy",
    component: _20495d84,
    name: "privacy___ar"
  }, {
    path: "/ar/products",
    component: _7132969e,
    name: "products___ar"
  }, {
    path: "/ar/result",
    component: _8211a96a,
    name: "result___ar"
  }, {
    path: "/ar/test",
    component: _b1193868,
    name: "test___ar"
  }, {
    path: "/da/about",
    component: _4016f643,
    name: "about___da"
  }, {
    path: "/da/agreeableness",
    component: _54bbd613,
    name: "agreeableness___da"
  }, {
    path: "/da/articles",
    component: _1d3982f7,
    name: "articles___da"
  }, {
    path: "/da/big_five",
    component: _6ba7b94b,
    name: "big_five___da"
  }, {
    path: "/da/compare",
    component: _4947c7f2,
    name: "compare___da"
  }, {
    path: "/da/conscientiousness",
    component: _6331a585,
    name: "conscientiousness___da"
  }, {
    path: "/da/extraversion",
    component: _f42fadfc,
    name: "extraversion___da"
  }, {
    path: "/da/faq",
    component: _3ac980cc,
    name: "faq___da"
  }, {
    path: "/da/neuroticism",
    component: _6282eff4,
    name: "neuroticism___da"
  }, {
    path: "/da/openness_to_experience",
    component: _c6157d6c,
    name: "openness_to_experience___da"
  }, {
    path: "/da/privacy",
    component: _20495d84,
    name: "privacy___da"
  }, {
    path: "/da/products",
    component: _7132969e,
    name: "products___da"
  }, {
    path: "/da/result",
    component: _8211a96a,
    name: "result___da"
  }, {
    path: "/da/test",
    component: _b1193868,
    name: "test___da"
  }, {
    path: "/de/about",
    component: _4016f643,
    name: "about___de"
  }, {
    path: "/de/agreeableness",
    component: _54bbd613,
    name: "agreeableness___de"
  }, {
    path: "/de/articles",
    component: _1d3982f7,
    name: "articles___de"
  }, {
    path: "/de/big_five",
    component: _6ba7b94b,
    name: "big_five___de"
  }, {
    path: "/de/compare",
    component: _4947c7f2,
    name: "compare___de"
  }, {
    path: "/de/conscientiousness",
    component: _6331a585,
    name: "conscientiousness___de"
  }, {
    path: "/de/extraversion",
    component: _f42fadfc,
    name: "extraversion___de"
  }, {
    path: "/de/faq",
    component: _3ac980cc,
    name: "faq___de"
  }, {
    path: "/de/neuroticism",
    component: _6282eff4,
    name: "neuroticism___de"
  }, {
    path: "/de/openness_to_experience",
    component: _c6157d6c,
    name: "openness_to_experience___de"
  }, {
    path: "/de/privacy",
    component: _20495d84,
    name: "privacy___de"
  }, {
    path: "/de/products",
    component: _7132969e,
    name: "products___de"
  }, {
    path: "/de/result",
    component: _8211a96a,
    name: "result___de"
  }, {
    path: "/de/test",
    component: _b1193868,
    name: "test___de"
  }, {
    path: "/es/about",
    component: _4016f643,
    name: "about___es"
  }, {
    path: "/es/agreeableness",
    component: _54bbd613,
    name: "agreeableness___es"
  }, {
    path: "/es/articles",
    component: _1d3982f7,
    name: "articles___es"
  }, {
    path: "/es/big_five",
    component: _6ba7b94b,
    name: "big_five___es"
  }, {
    path: "/es/compare",
    component: _4947c7f2,
    name: "compare___es"
  }, {
    path: "/es/conscientiousness",
    component: _6331a585,
    name: "conscientiousness___es"
  }, {
    path: "/es/extraversion",
    component: _f42fadfc,
    name: "extraversion___es"
  }, {
    path: "/es/faq",
    component: _3ac980cc,
    name: "faq___es"
  }, {
    path: "/es/neuroticism",
    component: _6282eff4,
    name: "neuroticism___es"
  }, {
    path: "/es/openness_to_experience",
    component: _c6157d6c,
    name: "openness_to_experience___es"
  }, {
    path: "/es/privacy",
    component: _20495d84,
    name: "privacy___es"
  }, {
    path: "/es/products",
    component: _7132969e,
    name: "products___es"
  }, {
    path: "/es/result",
    component: _8211a96a,
    name: "result___es"
  }, {
    path: "/es/test",
    component: _b1193868,
    name: "test___es"
  }, {
    path: "/fi/about",
    component: _4016f643,
    name: "about___fi"
  }, {
    path: "/fi/agreeableness",
    component: _54bbd613,
    name: "agreeableness___fi"
  }, {
    path: "/fi/articles",
    component: _1d3982f7,
    name: "articles___fi"
  }, {
    path: "/fi/big_five",
    component: _6ba7b94b,
    name: "big_five___fi"
  }, {
    path: "/fi/compare",
    component: _4947c7f2,
    name: "compare___fi"
  }, {
    path: "/fi/conscientiousness",
    component: _6331a585,
    name: "conscientiousness___fi"
  }, {
    path: "/fi/extraversion",
    component: _f42fadfc,
    name: "extraversion___fi"
  }, {
    path: "/fi/faq",
    component: _3ac980cc,
    name: "faq___fi"
  }, {
    path: "/fi/neuroticism",
    component: _6282eff4,
    name: "neuroticism___fi"
  }, {
    path: "/fi/openness_to_experience",
    component: _c6157d6c,
    name: "openness_to_experience___fi"
  }, {
    path: "/fi/privacy",
    component: _20495d84,
    name: "privacy___fi"
  }, {
    path: "/fi/products",
    component: _7132969e,
    name: "products___fi"
  }, {
    path: "/fi/result",
    component: _8211a96a,
    name: "result___fi"
  }, {
    path: "/fi/test",
    component: _b1193868,
    name: "test___fi"
  }, {
    path: "/fr/about",
    component: _4016f643,
    name: "about___fr"
  }, {
    path: "/fr/agreeableness",
    component: _54bbd613,
    name: "agreeableness___fr"
  }, {
    path: "/fr/articles",
    component: _1d3982f7,
    name: "articles___fr"
  }, {
    path: "/fr/big_five",
    component: _6ba7b94b,
    name: "big_five___fr"
  }, {
    path: "/fr/compare",
    component: _4947c7f2,
    name: "compare___fr"
  }, {
    path: "/fr/conscientiousness",
    component: _6331a585,
    name: "conscientiousness___fr"
  }, {
    path: "/fr/extraversion",
    component: _f42fadfc,
    name: "extraversion___fr"
  }, {
    path: "/fr/faq",
    component: _3ac980cc,
    name: "faq___fr"
  }, {
    path: "/fr/neuroticism",
    component: _6282eff4,
    name: "neuroticism___fr"
  }, {
    path: "/fr/openness_to_experience",
    component: _c6157d6c,
    name: "openness_to_experience___fr"
  }, {
    path: "/fr/privacy",
    component: _20495d84,
    name: "privacy___fr"
  }, {
    path: "/fr/products",
    component: _7132969e,
    name: "products___fr"
  }, {
    path: "/fr/result",
    component: _8211a96a,
    name: "result___fr"
  }, {
    path: "/fr/test",
    component: _b1193868,
    name: "test___fr"
  }, {
    path: "/hi/about",
    component: _4016f643,
    name: "about___hi"
  }, {
    path: "/hi/agreeableness",
    component: _54bbd613,
    name: "agreeableness___hi"
  }, {
    path: "/hi/articles",
    component: _1d3982f7,
    name: "articles___hi"
  }, {
    path: "/hi/big_five",
    component: _6ba7b94b,
    name: "big_five___hi"
  }, {
    path: "/hi/compare",
    component: _4947c7f2,
    name: "compare___hi"
  }, {
    path: "/hi/conscientiousness",
    component: _6331a585,
    name: "conscientiousness___hi"
  }, {
    path: "/hi/extraversion",
    component: _f42fadfc,
    name: "extraversion___hi"
  }, {
    path: "/hi/faq",
    component: _3ac980cc,
    name: "faq___hi"
  }, {
    path: "/hi/neuroticism",
    component: _6282eff4,
    name: "neuroticism___hi"
  }, {
    path: "/hi/openness_to_experience",
    component: _c6157d6c,
    name: "openness_to_experience___hi"
  }, {
    path: "/hi/privacy",
    component: _20495d84,
    name: "privacy___hi"
  }, {
    path: "/hi/products",
    component: _7132969e,
    name: "products___hi"
  }, {
    path: "/hi/result",
    component: _8211a96a,
    name: "result___hi"
  }, {
    path: "/hi/test",
    component: _b1193868,
    name: "test___hi"
  }, {
    path: "/id/about",
    component: _4016f643,
    name: "about___id"
  }, {
    path: "/id/agreeableness",
    component: _54bbd613,
    name: "agreeableness___id"
  }, {
    path: "/id/articles",
    component: _1d3982f7,
    name: "articles___id"
  }, {
    path: "/id/big_five",
    component: _6ba7b94b,
    name: "big_five___id"
  }, {
    path: "/id/compare",
    component: _4947c7f2,
    name: "compare___id"
  }, {
    path: "/id/conscientiousness",
    component: _6331a585,
    name: "conscientiousness___id"
  }, {
    path: "/id/extraversion",
    component: _f42fadfc,
    name: "extraversion___id"
  }, {
    path: "/id/faq",
    component: _3ac980cc,
    name: "faq___id"
  }, {
    path: "/id/neuroticism",
    component: _6282eff4,
    name: "neuroticism___id"
  }, {
    path: "/id/openness_to_experience",
    component: _c6157d6c,
    name: "openness_to_experience___id"
  }, {
    path: "/id/privacy",
    component: _20495d84,
    name: "privacy___id"
  }, {
    path: "/id/products",
    component: _7132969e,
    name: "products___id"
  }, {
    path: "/id/result",
    component: _8211a96a,
    name: "result___id"
  }, {
    path: "/id/test",
    component: _b1193868,
    name: "test___id"
  }, {
    path: "/is/about",
    component: _4016f643,
    name: "about___is"
  }, {
    path: "/is/agreeableness",
    component: _54bbd613,
    name: "agreeableness___is"
  }, {
    path: "/is/articles",
    component: _1d3982f7,
    name: "articles___is"
  }, {
    path: "/is/big_five",
    component: _6ba7b94b,
    name: "big_five___is"
  }, {
    path: "/is/compare",
    component: _4947c7f2,
    name: "compare___is"
  }, {
    path: "/is/conscientiousness",
    component: _6331a585,
    name: "conscientiousness___is"
  }, {
    path: "/is/extraversion",
    component: _f42fadfc,
    name: "extraversion___is"
  }, {
    path: "/is/faq",
    component: _3ac980cc,
    name: "faq___is"
  }, {
    path: "/is/neuroticism",
    component: _6282eff4,
    name: "neuroticism___is"
  }, {
    path: "/is/openness_to_experience",
    component: _c6157d6c,
    name: "openness_to_experience___is"
  }, {
    path: "/is/privacy",
    component: _20495d84,
    name: "privacy___is"
  }, {
    path: "/is/products",
    component: _7132969e,
    name: "products___is"
  }, {
    path: "/is/result",
    component: _8211a96a,
    name: "result___is"
  }, {
    path: "/is/test",
    component: _b1193868,
    name: "test___is"
  }, {
    path: "/it/about",
    component: _4016f643,
    name: "about___it"
  }, {
    path: "/it/agreeableness",
    component: _54bbd613,
    name: "agreeableness___it"
  }, {
    path: "/it/articles",
    component: _1d3982f7,
    name: "articles___it"
  }, {
    path: "/it/big_five",
    component: _6ba7b94b,
    name: "big_five___it"
  }, {
    path: "/it/compare",
    component: _4947c7f2,
    name: "compare___it"
  }, {
    path: "/it/conscientiousness",
    component: _6331a585,
    name: "conscientiousness___it"
  }, {
    path: "/it/extraversion",
    component: _f42fadfc,
    name: "extraversion___it"
  }, {
    path: "/it/faq",
    component: _3ac980cc,
    name: "faq___it"
  }, {
    path: "/it/neuroticism",
    component: _6282eff4,
    name: "neuroticism___it"
  }, {
    path: "/it/openness_to_experience",
    component: _c6157d6c,
    name: "openness_to_experience___it"
  }, {
    path: "/it/privacy",
    component: _20495d84,
    name: "privacy___it"
  }, {
    path: "/it/products",
    component: _7132969e,
    name: "products___it"
  }, {
    path: "/it/result",
    component: _8211a96a,
    name: "result___it"
  }, {
    path: "/it/test",
    component: _b1193868,
    name: "test___it"
  }, {
    path: "/ja/about",
    component: _4016f643,
    name: "about___ja"
  }, {
    path: "/ja/agreeableness",
    component: _54bbd613,
    name: "agreeableness___ja"
  }, {
    path: "/ja/articles",
    component: _1d3982f7,
    name: "articles___ja"
  }, {
    path: "/ja/big_five",
    component: _6ba7b94b,
    name: "big_five___ja"
  }, {
    path: "/ja/compare",
    component: _4947c7f2,
    name: "compare___ja"
  }, {
    path: "/ja/conscientiousness",
    component: _6331a585,
    name: "conscientiousness___ja"
  }, {
    path: "/ja/extraversion",
    component: _f42fadfc,
    name: "extraversion___ja"
  }, {
    path: "/ja/faq",
    component: _3ac980cc,
    name: "faq___ja"
  }, {
    path: "/ja/neuroticism",
    component: _6282eff4,
    name: "neuroticism___ja"
  }, {
    path: "/ja/openness_to_experience",
    component: _c6157d6c,
    name: "openness_to_experience___ja"
  }, {
    path: "/ja/privacy",
    component: _20495d84,
    name: "privacy___ja"
  }, {
    path: "/ja/products",
    component: _7132969e,
    name: "products___ja"
  }, {
    path: "/ja/result",
    component: _8211a96a,
    name: "result___ja"
  }, {
    path: "/ja/test",
    component: _b1193868,
    name: "test___ja"
  }, {
    path: "/no/about",
    component: _4016f643,
    name: "about___no"
  }, {
    path: "/no/agreeableness",
    component: _54bbd613,
    name: "agreeableness___no"
  }, {
    path: "/no/articles",
    component: _1d3982f7,
    name: "articles___no"
  }, {
    path: "/no/big_five",
    component: _6ba7b94b,
    name: "big_five___no"
  }, {
    path: "/no/compare",
    component: _4947c7f2,
    name: "compare___no"
  }, {
    path: "/no/conscientiousness",
    component: _6331a585,
    name: "conscientiousness___no"
  }, {
    path: "/no/extraversion",
    component: _f42fadfc,
    name: "extraversion___no"
  }, {
    path: "/no/faq",
    component: _3ac980cc,
    name: "faq___no"
  }, {
    path: "/no/neuroticism",
    component: _6282eff4,
    name: "neuroticism___no"
  }, {
    path: "/no/openness_to_experience",
    component: _c6157d6c,
    name: "openness_to_experience___no"
  }, {
    path: "/no/privacy",
    component: _20495d84,
    name: "privacy___no"
  }, {
    path: "/no/products",
    component: _7132969e,
    name: "products___no"
  }, {
    path: "/no/result",
    component: _8211a96a,
    name: "result___no"
  }, {
    path: "/no/test",
    component: _b1193868,
    name: "test___no"
  }, {
    path: "/pl/about",
    component: _4016f643,
    name: "about___pl"
  }, {
    path: "/pl/agreeableness",
    component: _54bbd613,
    name: "agreeableness___pl"
  }, {
    path: "/pl/articles",
    component: _1d3982f7,
    name: "articles___pl"
  }, {
    path: "/pl/big_five",
    component: _6ba7b94b,
    name: "big_five___pl"
  }, {
    path: "/pl/compare",
    component: _4947c7f2,
    name: "compare___pl"
  }, {
    path: "/pl/conscientiousness",
    component: _6331a585,
    name: "conscientiousness___pl"
  }, {
    path: "/pl/extraversion",
    component: _f42fadfc,
    name: "extraversion___pl"
  }, {
    path: "/pl/faq",
    component: _3ac980cc,
    name: "faq___pl"
  }, {
    path: "/pl/neuroticism",
    component: _6282eff4,
    name: "neuroticism___pl"
  }, {
    path: "/pl/openness_to_experience",
    component: _c6157d6c,
    name: "openness_to_experience___pl"
  }, {
    path: "/pl/privacy",
    component: _20495d84,
    name: "privacy___pl"
  }, {
    path: "/pl/products",
    component: _7132969e,
    name: "products___pl"
  }, {
    path: "/pl/result",
    component: _8211a96a,
    name: "result___pl"
  }, {
    path: "/pl/test",
    component: _b1193868,
    name: "test___pl"
  }, {
    path: "/pt/about",
    component: _4016f643,
    name: "about___pt"
  }, {
    path: "/pt/agreeableness",
    component: _54bbd613,
    name: "agreeableness___pt"
  }, {
    path: "/pt/articles",
    component: _1d3982f7,
    name: "articles___pt"
  }, {
    path: "/pt/big_five",
    component: _6ba7b94b,
    name: "big_five___pt"
  }, {
    path: "/pt/compare",
    component: _4947c7f2,
    name: "compare___pt"
  }, {
    path: "/pt/conscientiousness",
    component: _6331a585,
    name: "conscientiousness___pt"
  }, {
    path: "/pt/extraversion",
    component: _f42fadfc,
    name: "extraversion___pt"
  }, {
    path: "/pt/faq",
    component: _3ac980cc,
    name: "faq___pt"
  }, {
    path: "/pt/neuroticism",
    component: _6282eff4,
    name: "neuroticism___pt"
  }, {
    path: "/pt/openness_to_experience",
    component: _c6157d6c,
    name: "openness_to_experience___pt"
  }, {
    path: "/pt/privacy",
    component: _20495d84,
    name: "privacy___pt"
  }, {
    path: "/pt/products",
    component: _7132969e,
    name: "products___pt"
  }, {
    path: "/pt/result",
    component: _8211a96a,
    name: "result___pt"
  }, {
    path: "/pt/test",
    component: _b1193868,
    name: "test___pt"
  }, {
    path: "/ru/about",
    component: _4016f643,
    name: "about___ru"
  }, {
    path: "/ru/agreeableness",
    component: _54bbd613,
    name: "agreeableness___ru"
  }, {
    path: "/ru/articles",
    component: _1d3982f7,
    name: "articles___ru"
  }, {
    path: "/ru/big_five",
    component: _6ba7b94b,
    name: "big_five___ru"
  }, {
    path: "/ru/compare",
    component: _4947c7f2,
    name: "compare___ru"
  }, {
    path: "/ru/conscientiousness",
    component: _6331a585,
    name: "conscientiousness___ru"
  }, {
    path: "/ru/extraversion",
    component: _f42fadfc,
    name: "extraversion___ru"
  }, {
    path: "/ru/faq",
    component: _3ac980cc,
    name: "faq___ru"
  }, {
    path: "/ru/neuroticism",
    component: _6282eff4,
    name: "neuroticism___ru"
  }, {
    path: "/ru/openness_to_experience",
    component: _c6157d6c,
    name: "openness_to_experience___ru"
  }, {
    path: "/ru/privacy",
    component: _20495d84,
    name: "privacy___ru"
  }, {
    path: "/ru/products",
    component: _7132969e,
    name: "products___ru"
  }, {
    path: "/ru/result",
    component: _8211a96a,
    name: "result___ru"
  }, {
    path: "/ru/test",
    component: _b1193868,
    name: "test___ru"
  }, {
    path: "/sv/about",
    component: _4016f643,
    name: "about___sv"
  }, {
    path: "/sv/agreeableness",
    component: _54bbd613,
    name: "agreeableness___sv"
  }, {
    path: "/sv/articles",
    component: _1d3982f7,
    name: "articles___sv"
  }, {
    path: "/sv/big_five",
    component: _6ba7b94b,
    name: "big_five___sv"
  }, {
    path: "/sv/compare",
    component: _4947c7f2,
    name: "compare___sv"
  }, {
    path: "/sv/conscientiousness",
    component: _6331a585,
    name: "conscientiousness___sv"
  }, {
    path: "/sv/extraversion",
    component: _f42fadfc,
    name: "extraversion___sv"
  }, {
    path: "/sv/faq",
    component: _3ac980cc,
    name: "faq___sv"
  }, {
    path: "/sv/neuroticism",
    component: _6282eff4,
    name: "neuroticism___sv"
  }, {
    path: "/sv/openness_to_experience",
    component: _c6157d6c,
    name: "openness_to_experience___sv"
  }, {
    path: "/sv/privacy",
    component: _20495d84,
    name: "privacy___sv"
  }, {
    path: "/sv/products",
    component: _7132969e,
    name: "products___sv"
  }, {
    path: "/sv/result",
    component: _8211a96a,
    name: "result___sv"
  }, {
    path: "/sv/test",
    component: _b1193868,
    name: "test___sv"
  }, {
    path: "/th/about",
    component: _4016f643,
    name: "about___th"
  }, {
    path: "/th/agreeableness",
    component: _54bbd613,
    name: "agreeableness___th"
  }, {
    path: "/th/articles",
    component: _1d3982f7,
    name: "articles___th"
  }, {
    path: "/th/big_five",
    component: _6ba7b94b,
    name: "big_five___th"
  }, {
    path: "/th/compare",
    component: _4947c7f2,
    name: "compare___th"
  }, {
    path: "/th/conscientiousness",
    component: _6331a585,
    name: "conscientiousness___th"
  }, {
    path: "/th/extraversion",
    component: _f42fadfc,
    name: "extraversion___th"
  }, {
    path: "/th/faq",
    component: _3ac980cc,
    name: "faq___th"
  }, {
    path: "/th/neuroticism",
    component: _6282eff4,
    name: "neuroticism___th"
  }, {
    path: "/th/openness_to_experience",
    component: _c6157d6c,
    name: "openness_to_experience___th"
  }, {
    path: "/th/privacy",
    component: _20495d84,
    name: "privacy___th"
  }, {
    path: "/th/products",
    component: _7132969e,
    name: "products___th"
  }, {
    path: "/th/result",
    component: _8211a96a,
    name: "result___th"
  }, {
    path: "/th/test",
    component: _b1193868,
    name: "test___th"
  }, {
    path: "/uk/about",
    component: _4016f643,
    name: "about___uk"
  }, {
    path: "/uk/agreeableness",
    component: _54bbd613,
    name: "agreeableness___uk"
  }, {
    path: "/uk/articles",
    component: _1d3982f7,
    name: "articles___uk"
  }, {
    path: "/uk/big_five",
    component: _6ba7b94b,
    name: "big_five___uk"
  }, {
    path: "/uk/compare",
    component: _4947c7f2,
    name: "compare___uk"
  }, {
    path: "/uk/conscientiousness",
    component: _6331a585,
    name: "conscientiousness___uk"
  }, {
    path: "/uk/extraversion",
    component: _f42fadfc,
    name: "extraversion___uk"
  }, {
    path: "/uk/faq",
    component: _3ac980cc,
    name: "faq___uk"
  }, {
    path: "/uk/neuroticism",
    component: _6282eff4,
    name: "neuroticism___uk"
  }, {
    path: "/uk/openness_to_experience",
    component: _c6157d6c,
    name: "openness_to_experience___uk"
  }, {
    path: "/uk/privacy",
    component: _20495d84,
    name: "privacy___uk"
  }, {
    path: "/uk/products",
    component: _7132969e,
    name: "products___uk"
  }, {
    path: "/uk/result",
    component: _8211a96a,
    name: "result___uk"
  }, {
    path: "/uk/test",
    component: _b1193868,
    name: "test___uk"
  }, {
    path: "/zh-Hans/about",
    component: _4016f643,
    name: "about___zh-Hans"
  }, {
    path: "/zh-Hans/agreeableness",
    component: _54bbd613,
    name: "agreeableness___zh-Hans"
  }, {
    path: "/zh-Hans/articles",
    component: _1d3982f7,
    name: "articles___zh-Hans"
  }, {
    path: "/zh-Hans/big_five",
    component: _6ba7b94b,
    name: "big_five___zh-Hans"
  }, {
    path: "/zh-Hans/compare",
    component: _4947c7f2,
    name: "compare___zh-Hans"
  }, {
    path: "/zh-Hans/conscientiousness",
    component: _6331a585,
    name: "conscientiousness___zh-Hans"
  }, {
    path: "/zh-Hans/extraversion",
    component: _f42fadfc,
    name: "extraversion___zh-Hans"
  }, {
    path: "/zh-Hans/faq",
    component: _3ac980cc,
    name: "faq___zh-Hans"
  }, {
    path: "/zh-Hans/neuroticism",
    component: _6282eff4,
    name: "neuroticism___zh-Hans"
  }, {
    path: "/zh-Hans/openness_to_experience",
    component: _c6157d6c,
    name: "openness_to_experience___zh-Hans"
  }, {
    path: "/zh-Hans/privacy",
    component: _20495d84,
    name: "privacy___zh-Hans"
  }, {
    path: "/zh-Hans/products",
    component: _7132969e,
    name: "products___zh-Hans"
  }, {
    path: "/zh-Hans/result",
    component: _8211a96a,
    name: "result___zh-Hans"
  }, {
    path: "/zh-Hans/test",
    component: _b1193868,
    name: "test___zh-Hans"
  }, {
    path: "/ar/compare/:id",
    component: _0d7f742f,
    name: "compare-id___ar"
  }, {
    path: "/ar/result/:id",
    component: _305d8473,
    name: "result-id___ar"
  }, {
    path: "/da/compare/:id",
    component: _0d7f742f,
    name: "compare-id___da"
  }, {
    path: "/da/result/:id",
    component: _305d8473,
    name: "result-id___da"
  }, {
    path: "/de/compare/:id",
    component: _0d7f742f,
    name: "compare-id___de"
  }, {
    path: "/de/result/:id",
    component: _305d8473,
    name: "result-id___de"
  }, {
    path: "/es/compare/:id",
    component: _0d7f742f,
    name: "compare-id___es"
  }, {
    path: "/es/result/:id",
    component: _305d8473,
    name: "result-id___es"
  }, {
    path: "/fi/compare/:id",
    component: _0d7f742f,
    name: "compare-id___fi"
  }, {
    path: "/fi/result/:id",
    component: _305d8473,
    name: "result-id___fi"
  }, {
    path: "/fr/compare/:id",
    component: _0d7f742f,
    name: "compare-id___fr"
  }, {
    path: "/fr/result/:id",
    component: _305d8473,
    name: "result-id___fr"
  }, {
    path: "/hi/compare/:id",
    component: _0d7f742f,
    name: "compare-id___hi"
  }, {
    path: "/hi/result/:id",
    component: _305d8473,
    name: "result-id___hi"
  }, {
    path: "/id/compare/:id",
    component: _0d7f742f,
    name: "compare-id___id"
  }, {
    path: "/id/result/:id",
    component: _305d8473,
    name: "result-id___id"
  }, {
    path: "/is/compare/:id",
    component: _0d7f742f,
    name: "compare-id___is"
  }, {
    path: "/is/result/:id",
    component: _305d8473,
    name: "result-id___is"
  }, {
    path: "/it/compare/:id",
    component: _0d7f742f,
    name: "compare-id___it"
  }, {
    path: "/it/result/:id",
    component: _305d8473,
    name: "result-id___it"
  }, {
    path: "/ja/compare/:id",
    component: _0d7f742f,
    name: "compare-id___ja"
  }, {
    path: "/ja/result/:id",
    component: _305d8473,
    name: "result-id___ja"
  }, {
    path: "/no/compare/:id",
    component: _0d7f742f,
    name: "compare-id___no"
  }, {
    path: "/no/result/:id",
    component: _305d8473,
    name: "result-id___no"
  }, {
    path: "/pl/compare/:id",
    component: _0d7f742f,
    name: "compare-id___pl"
  }, {
    path: "/pl/result/:id",
    component: _305d8473,
    name: "result-id___pl"
  }, {
    path: "/pt/compare/:id",
    component: _0d7f742f,
    name: "compare-id___pt"
  }, {
    path: "/pt/result/:id",
    component: _305d8473,
    name: "result-id___pt"
  }, {
    path: "/ru/compare/:id",
    component: _0d7f742f,
    name: "compare-id___ru"
  }, {
    path: "/ru/result/:id",
    component: _305d8473,
    name: "result-id___ru"
  }, {
    path: "/sv/compare/:id",
    component: _0d7f742f,
    name: "compare-id___sv"
  }, {
    path: "/sv/result/:id",
    component: _305d8473,
    name: "result-id___sv"
  }, {
    path: "/th/compare/:id",
    component: _0d7f742f,
    name: "compare-id___th"
  }, {
    path: "/th/result/:id",
    component: _305d8473,
    name: "result-id___th"
  }, {
    path: "/uk/compare/:id",
    component: _0d7f742f,
    name: "compare-id___uk"
  }, {
    path: "/uk/result/:id",
    component: _305d8473,
    name: "result-id___uk"
  }, {
    path: "/zh-Hans/compare/:id",
    component: _0d7f742f,
    name: "compare-id___zh-Hans"
  }, {
    path: "/zh-Hans/result/:id",
    component: _305d8473,
    name: "result-id___zh-Hans"
  }, {
    path: "/compare/:id",
    component: _0d7f742f,
    name: "compare-id___en"
  }, {
    path: "/result/:id",
    component: _305d8473,
    name: "result-id___en"
  }, {
    path: "/",
    component: _5fced108,
    name: "index___en"
  }],

  fallback: false
}

export function createRouter (ssrContext, config) {
  const base = (config.app && config.app.basePath) || routerOptions.base
  const router = new Router({ ...routerOptions, base  })

  // TODO: remove in Nuxt 3
  const originalPush = router.push
  router.push = function push (location, onComplete = emptyFn, onAbort) {
    return originalPush.call(this, location, onComplete, onAbort)
  }

  const resolve = router.resolve.bind(router)
  router.resolve = (to, current, append) => {
    if (typeof to === 'string') {
      to = normalizeURL(to)
    }
    return resolve(to, current, append)
  }

  return router
}
